/*
 * This file is generated by jOOQ.
 */
package com.astrokoala.database;


import com.astrokoala.database.routines.CreateNewUser;
import com.astrokoala.database.routines.GetUserInfoByEmail;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in Playbooks
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>Playbooks.create_new_user</code>
     */
    public static void createNewUser(Configuration configuration, String inemail, String inpass, String inusername) {
        CreateNewUser p = new CreateNewUser();
        p.setInemail(inemail);
        p.setInpass(inpass);
        p.setInusername(inusername);

        p.execute(configuration);
    }

    /**
     * Call <code>Playbooks.get_user_info_by_email</code>
     */
    public static GetUserInfoByEmail getUserInfoByEmail(Configuration configuration, String email) {
        GetUserInfoByEmail p = new GetUserInfoByEmail();
        p.setEmail(email);

        p.execute(configuration);
        return p;
    }
}
