/*
 * This file is generated by jOOQ.
 */
package com.astrokoala.database;


import com.astrokoala.database.tables.Users;


/**
 * Convenience access to all tables in Playbooks
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Playbooks.Users</code>.
     */
    public static final Users USERS = Users.USERS;
}
