/*
 * This file is generated by jOOQ.
 */
package com.astrokoala.database.routines;


import com.astrokoala.database.Playbooks;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreateNewUser extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 33761820;

    /**
     * The parameter <code>Playbooks.create_new_user.inEmail</code>.
     */
    public static final Parameter<String> INEMAIL = Internal.createParameter("inEmail", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Playbooks.create_new_user.inPass</code>.
     */
    public static final Parameter<String> INPASS = Internal.createParameter("inPass", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Playbooks.create_new_user.inUserName</code>.
     */
    public static final Parameter<String> INUSERNAME = Internal.createParameter("inUserName", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * Create a new routine call instance
     */
    public CreateNewUser() {
        super("create_new_user", Playbooks.PLAYBOOKS);

        addInParameter(INEMAIL);
        addInParameter(INPASS);
        addInParameter(INUSERNAME);
    }

    /**
     * Set the <code>inEmail</code> parameter IN value to the routine
     */
    public void setInemail(String value) {
        setValue(INEMAIL, value);
    }

    /**
     * Set the <code>inPass</code> parameter IN value to the routine
     */
    public void setInpass(String value) {
        setValue(INPASS, value);
    }

    /**
     * Set the <code>inUserName</code> parameter IN value to the routine
     */
    public void setInusername(String value) {
        setValue(INUSERNAME, value);
    }
}
