/*
 * This file is generated by jOOQ.
 */
package com.astrokoala.database.routines;


import com.astrokoala.database.Playbooks;

import java.time.LocalDate;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetUserInfoByEmail extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -427514943;

    /**
     * The parameter <code>Playbooks.get_user_info_by_email.email</code>.
     */
    public static final Parameter<String> EMAIL = Internal.createParameter("email", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Playbooks.get_user_info_by_email.id</code>.
     */
    public static final Parameter<Integer> ID = Internal.createParameter("id", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>Playbooks.get_user_info_by_email.username</code>.
     */
    public static final Parameter<String> USERNAME = Internal.createParameter("username", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Playbooks.get_user_info_by_email.pass</code>.
     */
    public static final Parameter<String> PASS = Internal.createParameter("pass", org.jooq.impl.SQLDataType.VARCHAR(255), false, false);

    /**
     * The parameter <code>Playbooks.get_user_info_by_email.create_date</code>.
     */
    public static final Parameter<LocalDate> CREATE_DATE = Internal.createParameter("create_date", org.jooq.impl.SQLDataType.LOCALDATE, false, false);

    /**
     * Create a new routine call instance
     */
    public GetUserInfoByEmail() {
        super("get_user_info_by_email", Playbooks.PLAYBOOKS);

        addInParameter(EMAIL);
        addOutParameter(ID);
        addOutParameter(USERNAME);
        addOutParameter(PASS);
        addOutParameter(CREATE_DATE);
    }

    /**
     * Set the <code>email</code> parameter IN value to the routine
     */
    public void setEmail(String value) {
        setValue(EMAIL, value);
    }

    /**
     * Get the <code>id</code> parameter OUT value from the routine
     */
    public Integer getId() {
        return get(ID);
    }

    /**
     * Get the <code>username</code> parameter OUT value from the routine
     */
    public String getUsername() {
        return get(USERNAME);
    }

    /**
     * Get the <code>pass</code> parameter OUT value from the routine
     */
    public String getPass() {
        return get(PASS);
    }

    /**
     * Get the <code>create_date</code> parameter OUT value from the routine
     */
    public LocalDate getCreateDate() {
        return get(CREATE_DATE);
    }
}
